const pupa = require("pupa")
const fs = require("fs")
// content/blog/2017-03-20-virtual-machines/index.md
const template = fs.readFileSync("./scripts/new-post/post.jsx.tpl", "utf8")

const main = async () => {
  const outputFile = pupa(template, {
    note: `!!!! NOTE\n  Don't edit this file directly.\n\n  This is autogenerated from the script\n  "${scriptName}"\n`,
    routes: JSON.stringify(routes),
    handlerFile: `../${ymlFilePath.replace(/serverless.yml$/, "handler.js")}`,
  })

  fs.writeFileSync("Name.js", outputFile, "utf8")
}

return main()
  .then(_ => {
    console.log("done")
    process.exit(0)
  })
  .catch(e => {
    console.log(e)
    process.exit(1)
  })
